TAROT_CARDS_DATA = [
    # Старшие арканы (Major Arcana)
    {"name": "Шут", "image": "0.png", "type": "major"},
    {"name": "Маг", "image":"1.png", "type": "major"},
    {"name": "Верховная Жрица", "image": "2.png", "type": "major"},
    {"name": "Императрица", "image": "3.png", "type": "major"},
    {"name": "Император", "image":"4.png", "type": "major"},
    {"name": "Иерофант", "image": "5.png", "type": "major"},
    {"name": "Влюбленные", "image": "6.png", "type": "major"},
    {"name": "Колесница", "image": "7.png", "type": "major"},
    {"name": "Сила", "image":"8.png", "type": "major"},
    {"name": "Отшельник", "image":"9.png", "type": "major"},
    {"name": "Колесо Фортуны", "image": "10.png", "type": "major"},
    {"name": "Справедливость", "image": "11.png", "type": "major"},
    {"name": "Повешенный", "image":"12.png", "type": "major"},
    {"name": "Смерть", "image": "13.jpg", "type": "major"},
    {"name": "Умеренность", "image": "14.png", "type": "major"},
    {"name": "Дьявол", "image": "15.png", "type": "major"},
    {"name": "Башня", "image": "16.png", "type": "major"},
    {"name": "Звезда", "image": "17.png", "type": "major"},
    {"name": "Луна", "image": "18.png", "type": "major"},
    {"name": "Солнце", "image":"19.png", "type": "major"},
    {"name": "Суд", "image": "20.png", "type": "major"},
    {"name": "Мир", "image":"21.png", "type": "major"},
    
    # Младшие арканы (Minor Arcana) - Жезлы (Wands)
    {"name": "Туз Жезлов", "image": "ace_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Двойка Жезлов", "image": "2_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Тройка Жезлов", "image": "3_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Четверка Жезлов", "image": "4_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Пятерка Жезлов", "image": "5_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Шестерка Жезлов", "image": "6_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Семерка Жезлов", "image": "7_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Восьмерка Жезлов", "image": "8_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Девятка Жезлов", "image": "9_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Десятка Жезлов", "image": "10_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Паж Жезлов", "image": "page_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Рыцарь Жезлов", "image": "kni_wands.png", "type": "minor", "suit": "wands"},
    {"name": "Королева Жезлов", "image": "q_wand.png", "type": "minor", "suit": "wands"},
    {"name": "Король Жезлов", "image": "k_wand.png", "type": "minor", "suit": "wands"},
    
    # Младшие арканы - Кубки (Cups)
    {"name": "Туз Кубков", "image": "ace_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Двойка Кубков", "image": "2_cups.png", "type": "minor", "suit": "cups"},
    {"name": "Тройка Кубков", "image": "3_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Четверка Кубков", "image": "4_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Пятерка Кубков", "image": "5_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Шестерка Кубков", "image": "6_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Семерка Кубков", "image": "7_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Восьмерка Кубков", "image": "8_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Девятка Кубков", "image": "9_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Десятка Кубков", "image": "10_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Паж Кубков", "image": "page_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Рыцарь Кубков", "image": "kni_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Королева Кубков", "image": "q_cup.png", "type": "minor", "suit": "cups"},
    {"name": "Король Кубков", "image": "k_cups.png", "type": "minor", "suit": "cups"},
    
    # Младшие арканы - Мечи (Swords)
    {"name": "Туз Мечей", "image": "ace_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Двойка Мечей", "image": "2_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Тройка Мечей", "image": "3_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Четверка Мечей", "image": "4_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Пятерка Мечей", "image": "5_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Шестерка Мечей", "image": "6_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Семерка Мечей", "image": "7_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Восьмерка Мечей", "image": "8_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Девятка Мечей", "image": "9_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Десятка Мечей", "image": "10_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Паж Мечей", "image": "page_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Рыцарь Мечей", "image": "kni_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Королева Мечей", "image": "q_swo.png", "type": "minor", "suit": "swords"},
    {"name": "Король Мечей", "image": "k_swo.png", "type": "minor", "suit": "swords"},
    
    # Младшие арканы - Пентакли (Pentacles)
    {"name": "Туз Пентаклей", "image": "ace_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Двойка Пентаклей", "image": "2_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Тройка Пентаклей", "image": "3_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Четверка Пентаклей", "image": "4_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Пятерка Пентаклей", "image": "5_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Шестерка Пентаклей", "image": "6_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Семерка Пентаклей", "image": "7_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Восьмерка Пентаклей", "image": "8_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Девятка Пентаклей", "image": "9_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Десятка Пентаклей", "image": "10_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Паж Пентаклей", "image": "page_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Рыцарь Пентаклей", "image": "kni_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Королева Пентаклей", "image": "q_pent.png", "type": "minor", "suit": "pentacles"},
    {"name": "Король Пентаклей", "image": "k_pent.png", "type": "minor", "suit": "pentacles"},
]
